version: "3.1"

services:
  mongo:
    image: mongo:7.0.3
    container_name: blog-mongo
    restart: always
    ports:
      - 27017:27017
  redis:
    image: "redis:7.2.3-alpine"
    container_name: blog-redis
    ports:
      - "6379:6379"
